"""User account lock out

Revision ID: 0831f9c70d68
Revises: d14c7a3fd28c
Create Date: 2020-09-14 15:18:04.599837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0831f9c70d68'
down_revision = 'd14c7a3fd28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locked_ind', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_ind')
    # ### end Alembic commands ###
